//! The wire contract, and what the log records.
//!
//! Two shapes, on purpose:
//!
//! * [`EventEnvelope`] is what a Python or TypeScript SDK publishes. Flat,
//!   `snake_case`, and almost entirely optional — a producer should be able to
//!   send a useful event knowing only `event_type`, `run_id` and `occurred_at`.
//! * [`RecordedEvent`] is what the log hands to a consumer. It is Emmett's
//!   `RecordedMessage`: the producer's `kind` / `type` / `data` plus a metadata
//!   block the *store* fills in — positions, checkpoint, and the four resolved
//!   correlation ids.
//!
//! [`EventEnvelope::record`] is the one place a partial envelope becomes a
//! complete record. Everything downstream can then rely on every field being
//! present, which is what keeps the projector free of `Option` handling.

use serde::{Deserialize, Serialize};
use time::OffsetDateTime;

use crate::catalog::EventType;
use crate::checkpoint::Checkpoint;
use crate::context::{ObservabilityContext, ResolveTarget, SeedContext};
use crate::error::CoreError;
use crate::ids::{CausationId, CorrelationId, MessageId, SpanId, TraceId};
use crate::stream::{GlobalPosition, StreamName, StreamPosition};

/// The envelope version this build writes and the highest it can read.
pub const SCHEMA_VERSION: u16 = 1;

/// Emmett splits messages into commands and events; aiwatcher only ingests
/// events today, but the discriminator is on the wire from day one so adding
/// control commands later is not a breaking change.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "PascalCase")]
pub enum MessageKind {
    #[default]
    Event,
    Command,
}

/// Which SDK produced an event.
///
/// Serialised as a plain string with an unknown value passing through: an SDK
/// this backend has never heard of must still be able to publish.
#[derive(Clone, Debug, PartialEq, Eq, utoipa::ToSchema)]
pub enum Sdk {
    Python,
    Typescript,
    Rust,
    Other(String),
}

impl Sdk {
    #[must_use]
    pub fn as_str(&self) -> &str {
        match self {
            Self::Python => "python",
            Self::Typescript => "typescript",
            Self::Rust => "rust",
            Self::Other(raw) => raw.as_str(),
        }
    }

    #[must_use]
    pub fn parse(value: &str) -> Self {
        match value {
            "python" => Self::Python,
            "typescript" => Self::Typescript,
            "rust" => Self::Rust,
            other => Self::Other(other.to_owned()),
        }
    }
}

impl Serialize for Sdk {
    fn serialize<S: serde::Serializer>(&self, ser: S) -> Result<S::Ok, S::Error> {
        ser.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for Sdk {
    fn deserialize<D: serde::Deserializer<'de>>(de: D) -> Result<Self, D::Error> {
        Ok(Self::parse(&String::deserialize(de)?))
    }
}

/// Who sent the event. Enough to find the process that produced a bad batch.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, utoipa::ToSchema)]
pub struct Source {
    pub service: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub instance: Option<String>,
    pub sdk: Sdk,
}

impl Source {
    pub fn new(service: impl Into<String>, sdk: Sdk) -> Self {
        Self {
            service: service.into(),
            instance: None,
            sdk,
        }
    }
}

/// What a producer publishes.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, utoipa::ToSchema)]
pub struct EventEnvelope {
    /// Contract version. An envelope from the future is rejected rather than
    /// silently half-read.
    #[serde(default = "default_schema_version")]
    pub schema_version: u16,

    #[serde(default)]
    pub kind: MessageKind,

    /// Deduplication key. Generated by the ingest edge when absent, which
    /// means a producer that omits it gets at-least-once *without*
    /// deduplication — say so in the SDK docs.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub event_id: Option<MessageId>,

    /// e.g. `llm.completed`. See [`crate::catalog`].
    pub event_type: EventType,

    /// When the producer observed it. Distinct from `ingested_at`, which the
    /// ingest edge stamps — the gap between them is producer lag.
    #[serde(with = "time::serde::rfc3339")]
    pub occurred_at: OffsetDateTime,

    /// One execution of an agent. This is what a trace is scoped to.
    pub run_id: String,

    /// Groups several runs a user would think of as one conversation.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conversation_id: Option<String>,

    /// Which orchestration this run is an execution of.
    ///
    /// A conversation groups runs by *who* is talking; a workflow groups them
    /// by *what* is being executed. The same workflow runs across many
    /// sessions, which is the comparison — this graph, before and after a
    /// change — that `conversation_id` cannot express.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub workflow_id: Option<String>,

    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent_id: Option<String>,

    /// Producer-side counter within the run. Gaps here mean lost events; it is
    /// the only way to notice a producer that dropped a batch.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sequence: Option<u64>,

    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub trace_id: Option<TraceId>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub span_id: Option<SpanId>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parent_span_id: Option<SpanId>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub correlation_id: Option<CorrelationId>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub causation_id: Option<CausationId>,

    pub source: Source,

    /// Type-specific payload. Kept as free-form JSON so an SDK can add a field
    /// without a backend release.
    #[serde(default)]
    #[schema(value_type = Object)]
    pub data: serde_json::Value,
}

fn default_schema_version() -> u16 {
    SCHEMA_VERSION
}

impl EventEnvelope {
    /// Minimal well-formed envelope, for tests and for the Rust SDK.
    pub fn new(
        event_type: EventType,
        run_id: impl Into<String>,
        occurred_at: OffsetDateTime,
        source: Source,
    ) -> Self {
        Self {
            schema_version: SCHEMA_VERSION,
            kind: MessageKind::Event,
            event_id: None,
            event_type,
            occurred_at,
            run_id: run_id.into(),
            conversation_id: None,
            workflow_id: None,
            agent_id: None,
            sequence: None,
            trace_id: None,
            span_id: None,
            parent_span_id: None,
            correlation_id: None,
            causation_id: None,
            source,
            data: serde_json::Value::Null,
        }
    }

    #[must_use]
    pub fn with_data(mut self, data: serde_json::Value) -> Self {
        self.data = data;
        self
    }

    /// The id that separates two concurrent LLM or tool calls inside one agent.
    ///
    /// Read from `data.call_id`, falling back to `data.tool_call_id` so a
    /// tool-flavoured SDK does not have to duplicate the field.
    #[must_use]
    pub fn call_id(&self) -> Option<&str> {
        self.data
            .get("call_id")
            .or_else(|| self.data.get("tool_call_id"))
            .and_then(serde_json::Value::as_str)
    }

    /// The workflow this run executes, falling back to the payload.
    ///
    /// `workflow_id` is the field to set, but the name has been travelling in
    /// `data.workflow` since before there was a field for it — the `agentic`
    /// integration puts it there on `run.started`. Reading both means the
    /// dimension lights up for producers that never ship an SDK update.
    #[must_use]
    pub fn workflow(&self) -> Option<String> {
        if let Some(id) = &self.workflow_id {
            return Some(id.clone());
        }
        self.data
            .get("workflow")
            .or_else(|| self.data.get("workflow_id"))
            .or_else(|| self.data.get("workflow_name"))
            .and_then(serde_json::Value::as_str)
            .map(ToOwned::to_owned)
    }

    /// Reject what cannot be recorded. Everything else is repaired in
    /// [`Self::record`].
    pub fn validate(&self) -> Result<(), CoreError> {
        if self.schema_version > SCHEMA_VERSION {
            return Err(CoreError::UnsupportedSchemaVersion {
                found: self.schema_version,
                supported: SCHEMA_VERSION,
            });
        }
        if self.run_id.is_empty() {
            return Err(CoreError::MissingField {
                event_id: self
                    .event_id
                    .as_ref()
                    .map_or_else(|| "<unset>".to_owned(), ToString::to_string),
                event_type: self.event_type.to_string(),
                field: "run_id",
            });
        }
        if self.source.service.is_empty() {
            return Err(CoreError::MissingField {
                event_id: self
                    .event_id
                    .as_ref()
                    .map_or_else(|| "<unset>".to_owned(), ToString::to_string),
                event_type: self.event_type.to_string(),
                field: "source.service",
            });
        }
        Ok(())
    }

    /// The stream this event belongs on: one per run.
    #[must_use]
    pub fn stream_name(&self) -> StreamName {
        StreamName::for_run(&self.run_id)
    }

    /// Promote a producer envelope into a log record.
    ///
    /// `inherited` is the context of the *parent* operation when the ingest
    /// side knows it (a projector that already has the agent's span open, say).
    /// Passing `None` is fine and common: the ids then derive from `run_id` and
    /// the span key, which is exactly what makes a replay reproduce them.
    #[must_use]
    pub fn record(
        self,
        stream_position: StreamPosition,
        global_position: GlobalPosition,
        ingested_at: OffsetDateTime,
        inherited: Option<&ObservabilityContext>,
    ) -> RecordedEvent {
        let message_id = self.event_id.clone().unwrap_or_else(MessageId::generate);
        let workflow_id = self.workflow();
        let span_key = self
            .event_type
            .span_key(self.call_id(), self.agent_id.as_deref());
        let seed = SeedContext {
            trace_id: self.trace_id,
            span_id: self.span_id,
            parent_span_id: self.parent_span_id,
            correlation_id: self.correlation_id.clone(),
            causation_id: self.causation_id.clone(),
        };
        let context = ObservabilityContext::resolve(
            &seed,
            inherited,
            ResolveTarget {
                run_id: &self.run_id,
                span_key: &span_key,
            },
            &message_id,
        );

        RecordedEvent {
            kind: self.kind,
            event_type: self.event_type,
            data: self.data,
            metadata: RecordedMetadata {
                message_id,
                stream_name: StreamName::for_run(&self.run_id),
                stream_position,
                global_position,
                checkpoint: Checkpoint::from_global_position(global_position),
                trace_id: context.trace_id,
                span_id: context.span_id,
                parent_span_id: context.parent_span_id,
                correlation_id: context.correlation_id,
                causation_id: context.causation_id,
                run_id: self.run_id,
                conversation_id: self.conversation_id,
                workflow_id,
                agent_id: self.agent_id,
                sequence: self.sequence,
                span_key,
                schema_version: self.schema_version,
                source: self.source,
                occurred_at: self.occurred_at,
                ingested_at,
            },
        }
    }
}

/// What the store fills in. Emmett's `RecordedMessageMetadata`, plus the
/// aiwatcher-specific identity fields a projector would otherwise dig out of
/// `data` on every event.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, utoipa::ToSchema)]
pub struct RecordedMetadata {
    pub message_id: MessageId,
    pub stream_name: StreamName,
    // Inlined rather than referenced: the aliases are `u64`, and utoipa would
    // otherwise emit a component literally named `u64` for the generated
    // TypeScript to import.
    #[schema(value_type = u64, minimum = 0)]
    pub stream_position: StreamPosition,
    #[schema(value_type = u64, minimum = 0)]
    pub global_position: GlobalPosition,
    pub checkpoint: Checkpoint,

    pub trace_id: TraceId,
    pub span_id: SpanId,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parent_span_id: Option<SpanId>,
    pub correlation_id: CorrelationId,
    pub causation_id: CausationId,

    pub run_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conversation_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub workflow_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub agent_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub sequence: Option<u64>,

    /// The key `span_id` derived from. Carried so a projector can group a
    /// start and its end without re-deriving it.
    pub span_key: String,

    pub schema_version: u16,
    pub source: Source,

    #[serde(with = "time::serde::rfc3339")]
    pub occurred_at: OffsetDateTime,
    #[serde(with = "time::serde::rfc3339")]
    pub ingested_at: OffsetDateTime,
}

/// An event as a consumer sees it.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, utoipa::ToSchema)]
pub struct RecordedEvent {
    pub kind: MessageKind,
    pub event_type: EventType,
    #[schema(value_type = Object)]
    pub data: serde_json::Value,
    pub metadata: RecordedMetadata,
}

impl RecordedEvent {
    /// The resolved context, for seeding whatever this event causes.
    #[must_use]
    pub fn context(&self) -> ObservabilityContext {
        ObservabilityContext {
            trace_id: self.metadata.trace_id,
            span_id: self.metadata.span_id,
            parent_span_id: self.metadata.parent_span_id,
            correlation_id: self.metadata.correlation_id.clone(),
            causation_id: self.metadata.causation_id.clone(),
        }
    }

    /// A string field from the payload.
    #[must_use]
    pub fn data_str(&self, key: &str) -> Option<&str> {
        self.data.get(key).and_then(serde_json::Value::as_str)
    }

    /// An integer field from the payload, accepting a JSON float that happens
    /// to be whole — Python's `json` emits `812.0` for an int often enough that
    /// being strict here just loses token counts.
    #[must_use]
    pub fn data_i64(&self, key: &str) -> Option<i64> {
        let value = self.data.get(key)?;
        value.as_i64().or_else(|| {
            value
                .as_f64()
                .filter(|number| number.fract() == 0.0)
                .map(|number| number as i64)
        })
    }

    #[must_use]
    pub fn data_f64(&self, key: &str) -> Option<f64> {
        self.data.get(key).and_then(serde_json::Value::as_f64)
    }
}

#[cfg(test)]
mod tests {
    use time::macros::datetime;

    use super::*;

    fn envelope(event_type: EventType) -> EventEnvelope {
        EventEnvelope::new(
            event_type,
            "run-1",
            datetime!(2026-08-27 18:20:11 UTC),
            Source::new("python-agent-service", Sdk::Python),
        )
    }

    #[test]
    fn a_minimal_envelope_records_with_every_field_populated() {
        let recorded =
            envelope(EventType::RunStarted).record(1, 42, datetime!(2026-08-27 18:20:12 UTC), None);

        assert_eq!(recorded.metadata.stream_name.to_string(), "run:run-1");
        assert_eq!(recorded.metadata.stream_position, 1);
        assert_eq!(recorded.metadata.global_position, 42);
        assert_eq!(
            recorded.metadata.checkpoint,
            Checkpoint::from_global_position(42)
        );
        assert_eq!(recorded.metadata.trace_id, TraceId::derive("run-1"));
        // Nothing seeded a correlation, so it roots on the generated message id
        // and causation roots on the correlation.
        assert_eq!(
            recorded.metadata.correlation_id.as_str(),
            recorded.metadata.message_id.as_str()
        );
        assert_eq!(
            recorded.metadata.causation_id.as_str(),
            recorded.metadata.correlation_id.as_str()
        );
    }

    #[test]
    fn recording_the_same_envelope_twice_yields_the_same_span() {
        let mut source = envelope(EventType::LlmCompleted);
        source.event_id = Some(MessageId::new("evt-1"));
        source.agent_id = Some("researcher".to_owned());
        source.data = serde_json::json!({ "call_id": "call-7" });

        let first = source
            .clone()
            .record(3, 10, datetime!(2026-08-27 18:20:12 UTC), None);
        let second = source.record(3, 10, datetime!(2026-08-27 18:21:00 UTC), None);

        assert_eq!(first.metadata.trace_id, second.metadata.trace_id);
        assert_eq!(first.metadata.span_id, second.metadata.span_id);
        assert_eq!(first.metadata.span_key, second.metadata.span_key);
    }

    #[test]
    fn a_start_and_its_completion_share_a_span_id() {
        let mut started = envelope(EventType::LlmStarted);
        started.agent_id = Some("researcher".to_owned());
        started.data = serde_json::json!({ "call_id": "call-7" });
        let mut completed = envelope(EventType::LlmCompleted);
        completed.agent_id = Some("researcher".to_owned());
        completed.data = serde_json::json!({ "call_id": "call-7" });

        let started = started.record(1, 1, datetime!(2026-08-27 18:20:12 UTC), None);
        let completed = completed.record(2, 2, datetime!(2026-08-27 18:20:13 UTC), None);

        assert_eq!(started.metadata.span_id, completed.metadata.span_id);
    }

    #[test]
    fn an_envelope_from_a_newer_contract_is_rejected() {
        let mut future = envelope(EventType::RunStarted);
        future.schema_version = SCHEMA_VERSION + 1;
        assert!(matches!(
            future.validate(),
            Err(CoreError::UnsupportedSchemaVersion { .. })
        ));
    }

    #[test]
    fn an_envelope_without_a_run_is_rejected() {
        let mut orphan = envelope(EventType::RunStarted);
        orphan.run_id = String::new();
        assert!(matches!(
            orphan.validate(),
            Err(CoreError::MissingField {
                field: "run_id",
                ..
            })
        ));
    }

    #[test]
    fn a_workflow_id_is_read_from_the_run_started_payload_when_the_envelope_omits_it() {
        // The `agentic` integration has been sending the name in `data.workflow`
        // since before there was a field for it. Reading both is what lets the
        // dimension light up without an SDK release.
        let mut wire = envelope(EventType::RunStarted);
        wire.data = serde_json::json!({ "workflow": "nightly-summary" });

        let recorded = wire.record(1, 1, datetime!(2026-08-27 18:20:12 UTC), None);

        assert_eq!(
            recorded.metadata.workflow_id.as_deref(),
            Some("nightly-summary")
        );
    }

    #[test]
    fn an_explicit_workflow_id_wins_over_the_payload() {
        let mut wire = envelope(EventType::RunStarted);
        wire.workflow_id = Some("checkout-v2".to_owned());
        wire.data = serde_json::json!({ "workflow": "stale-name" });

        let recorded = wire.record(1, 1, datetime!(2026-08-27 18:20:12 UTC), None);

        assert_eq!(
            recorded.metadata.workflow_id.as_deref(),
            Some("checkout-v2")
        );
    }

    #[test]
    fn an_envelope_without_a_workflow_id_is_still_accepted() {
        let wire = envelope(EventType::RunStarted);

        wire.validate().expect("a workflow is optional");
        let recorded = wire.record(1, 1, datetime!(2026-08-27 18:20:12 UTC), None);

        assert!(recorded.metadata.workflow_id.is_none());
    }

    #[test]
    fn the_wire_form_is_flat_snake_case_json() {
        let mut wire = envelope(EventType::LlmCompleted);
        wire.event_id = Some(MessageId::new("01J8"));
        wire.conversation_id = Some("conv_123".to_owned());
        wire.agent_id = Some("research-agent".to_owned());
        wire.sequence = Some(17);
        wire.data = serde_json::json!({ "model": "claude-opus-5", "prompt_tokens": 812 });

        let json = serde_json::to_value(&wire).expect("serializes");
        assert_eq!(json["event_type"], "llm.completed");
        assert_eq!(json["event_id"], "01J8");
        assert_eq!(json["run_id"], "run-1");
        assert_eq!(json["conversation_id"], "conv_123");
        assert_eq!(json["sequence"], 17);
        assert_eq!(json["source"]["sdk"], "python");
        assert_eq!(json["occurred_at"], "2026-08-27T18:20:11Z");
        // Unset optionals stay off the wire rather than serialising as null.
        assert!(json.get("trace_id").is_none());

        let parsed: EventEnvelope = serde_json::from_value(json).expect("round trips");
        assert_eq!(parsed, wire);
    }

    #[test]
    fn an_unknown_sdk_and_event_type_survive_a_round_trip() {
        let raw = serde_json::json!({
            "event_type": "guardrail.tripped",
            "occurred_at": "2026-08-27T18:20:11Z",
            "run_id": "run-1",
            "source": { "service": "svc", "sdk": "elixir" },
            "data": {}
        });
        let parsed: EventEnvelope = serde_json::from_value(raw).expect("tolerates the unknown");
        assert_eq!(parsed.event_type.as_str(), "guardrail.tripped");
        assert_eq!(parsed.source.sdk.as_str(), "elixir");
        assert_eq!(parsed.schema_version, SCHEMA_VERSION);
        assert!(parsed.validate().is_ok());
    }

    #[test]
    fn token_counts_survive_a_python_float() {
        let recorded = envelope(EventType::LlmCompleted)
            .with_data(serde_json::json!({ "prompt_tokens": 812.0, "duration_ms": 1240 }))
            .record(1, 1, datetime!(2026-08-27 18:20:12 UTC), None);
        assert_eq!(recorded.data_i64("prompt_tokens"), Some(812));
        assert_eq!(recorded.data_i64("duration_ms"), Some(1240));
        assert_eq!(recorded.data_i64("missing"), None);
    }

    #[test]
    fn a_child_event_inherits_the_parents_flow() {
        let parent = envelope(EventType::AgentStarted).record(
            1,
            1,
            datetime!(2026-08-27 18:20:12 UTC),
            None,
        );
        let child = envelope(EventType::LlmStarted).record(
            2,
            2,
            datetime!(2026-08-27 18:20:13 UTC),
            Some(&parent.context()),
        );

        assert_eq!(child.metadata.trace_id, parent.metadata.trace_id);
        assert_eq!(child.metadata.parent_span_id, Some(parent.metadata.span_id));
        assert_eq!(
            child.metadata.correlation_id,
            parent.metadata.correlation_id
        );
    }
}
