/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DatasetsRouteImport } from './routes/datasets'
import { Route as EvaluationRouteImport } from './routes/evaluation'
import { Route as ExperimentsRouteImport } from './routes/experiments'
import { Route as ObservabilityRouteImport } from './routes/observability'
import { Route as ObservabilityIndexRouteImport } from './routes/observability.index'
import { Route as ObservabilityExploreRouteImport } from './routes/observability.explore'
import { Route as ObservabilityMetricsRouteImport } from './routes/observability.metrics'
import { Route as ObservabilityQueryRouteImport } from './routes/observability.query'
import { Route as ObservabilityRunsRouteImport } from './routes/observability.runs'
import { Route as PromptsIndexRouteImport } from './routes/prompts.index'
import { Route as PromptsNameRouteImport } from './routes/prompts.$name'
import { Route as RunsRunIdRouteImport } from './routes/runs.$runId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsRoute = DatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationRoute = EvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsRoute = ExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservabilityRoute = ObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservabilityIndexRoute = ObservabilityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ObservabilityRoute,
} as any)
const ObservabilityExploreRoute = ObservabilityExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => ObservabilityRoute,
} as any)
const ObservabilityMetricsRoute = ObservabilityMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => ObservabilityRoute,
} as any)
const ObservabilityQueryRoute = ObservabilityQueryRouteImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => ObservabilityRoute,
} as any)
const ObservabilityRunsRoute = ObservabilityRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => ObservabilityRoute,
} as any)
const PromptsIndexRoute = PromptsIndexRouteImport.update({
  id: '/prompts/',
  path: '/prompts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsNameRoute = PromptsNameRouteImport.update({
  id: '/prompts/$name',
  path: '/prompts/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datasets': typeof DatasetsRoute
  '/evaluation': typeof EvaluationRoute
  '/experiments': typeof ExperimentsRoute
  '/observability': typeof ObservabilityRouteWithChildren
  '/observability/explore': typeof ObservabilityExploreRoute
  '/observability/metrics': typeof ObservabilityMetricsRoute
  '/observability/query': typeof ObservabilityQueryRoute
  '/observability/runs': typeof ObservabilityRunsRoute
  '/prompts/$name': typeof PromptsNameRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/observability/': typeof ObservabilityIndexRoute
  '/prompts/': typeof PromptsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datasets': typeof DatasetsRoute
  '/evaluation': typeof EvaluationRoute
  '/experiments': typeof ExperimentsRoute
  '/observability/explore': typeof ObservabilityExploreRoute
  '/observability/metrics': typeof ObservabilityMetricsRoute
  '/observability/query': typeof ObservabilityQueryRoute
  '/observability/runs': typeof ObservabilityRunsRoute
  '/prompts/$name': typeof PromptsNameRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/observability': typeof ObservabilityIndexRoute
  '/prompts': typeof PromptsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datasets': typeof DatasetsRoute
  '/evaluation': typeof EvaluationRoute
  '/experiments': typeof ExperimentsRoute
  '/observability': typeof ObservabilityRouteWithChildren
  '/observability/explore': typeof ObservabilityExploreRoute
  '/observability/metrics': typeof ObservabilityMetricsRoute
  '/observability/query': typeof ObservabilityQueryRoute
  '/observability/runs': typeof ObservabilityRunsRoute
  '/prompts/$name': typeof PromptsNameRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/observability/': typeof ObservabilityIndexRoute
  '/prompts/': typeof PromptsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datasets'
    | '/evaluation'
    | '/experiments'
    | '/observability'
    | '/observability/explore'
    | '/observability/metrics'
    | '/observability/query'
    | '/observability/runs'
    | '/prompts/$name'
    | '/runs/$runId'
    | '/observability/'
    | '/prompts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datasets'
    | '/evaluation'
    | '/experiments'
    | '/observability/explore'
    | '/observability/metrics'
    | '/observability/query'
    | '/observability/runs'
    | '/prompts/$name'
    | '/runs/$runId'
    | '/observability'
    | '/prompts'
  id:
    | '__root__'
    | '/'
    | '/datasets'
    | '/evaluation'
    | '/experiments'
    | '/observability'
    | '/observability/explore'
    | '/observability/metrics'
    | '/observability/query'
    | '/observability/runs'
    | '/prompts/$name'
    | '/runs/$runId'
    | '/observability/'
    | '/prompts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatasetsRoute: typeof DatasetsRoute
  EvaluationRoute: typeof EvaluationRoute
  ExperimentsRoute: typeof ExperimentsRoute
  ObservabilityRoute: typeof ObservabilityRouteWithChildren
  PromptsNameRoute: typeof PromptsNameRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
  PromptsIndexRoute: typeof PromptsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets': {
      id: '/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof DatasetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation': {
      id: '/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments': {
      id: '/experiments'
      path: '/experiments'
      fullPath: '/experiments'
      preLoaderRoute: typeof ExperimentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observability': {
      id: '/observability'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof ObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observability/': {
      id: '/observability/'
      path: '/'
      fullPath: '/observability/'
      preLoaderRoute: typeof ObservabilityIndexRouteImport
      parentRoute: typeof ObservabilityRoute
    }
    '/observability/explore': {
      id: '/observability/explore'
      path: '/explore'
      fullPath: '/observability/explore'
      preLoaderRoute: typeof ObservabilityExploreRouteImport
      parentRoute: typeof ObservabilityRoute
    }
    '/observability/metrics': {
      id: '/observability/metrics'
      path: '/metrics'
      fullPath: '/observability/metrics'
      preLoaderRoute: typeof ObservabilityMetricsRouteImport
      parentRoute: typeof ObservabilityRoute
    }
    '/observability/query': {
      id: '/observability/query'
      path: '/query'
      fullPath: '/observability/query'
      preLoaderRoute: typeof ObservabilityQueryRouteImport
      parentRoute: typeof ObservabilityRoute
    }
    '/observability/runs': {
      id: '/observability/runs'
      path: '/runs'
      fullPath: '/observability/runs'
      preLoaderRoute: typeof ObservabilityRunsRouteImport
      parentRoute: typeof ObservabilityRoute
    }
    '/prompts/': {
      id: '/prompts/'
      path: '/prompts'
      fullPath: '/prompts/'
      preLoaderRoute: typeof PromptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts/$name': {
      id: '/prompts/$name'
      path: '/prompts/$name'
      fullPath: '/prompts/$name'
      preLoaderRoute: typeof PromptsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ObservabilityRouteChildren {
  ObservabilityExploreRoute: typeof ObservabilityExploreRoute
  ObservabilityMetricsRoute: typeof ObservabilityMetricsRoute
  ObservabilityQueryRoute: typeof ObservabilityQueryRoute
  ObservabilityRunsRoute: typeof ObservabilityRunsRoute
  ObservabilityIndexRoute: typeof ObservabilityIndexRoute
}

const ObservabilityRouteChildren: ObservabilityRouteChildren = {
  ObservabilityExploreRoute: ObservabilityExploreRoute,
  ObservabilityMetricsRoute: ObservabilityMetricsRoute,
  ObservabilityQueryRoute: ObservabilityQueryRoute,
  ObservabilityRunsRoute: ObservabilityRunsRoute,
  ObservabilityIndexRoute: ObservabilityIndexRoute,
}

const ObservabilityRouteWithChildren = ObservabilityRoute._addFileChildren(
  ObservabilityRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatasetsRoute: DatasetsRoute,
  EvaluationRoute: EvaluationRoute,
  ExperimentsRoute: ExperimentsRoute,
  ObservabilityRoute: ObservabilityRouteWithChildren,
  PromptsNameRoute: PromptsNameRoute,
  RunsRunIdRoute: RunsRunIdRoute,
  PromptsIndexRoute: PromptsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
