/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnnotationsRouteImport } from './routes/annotations'
import { Route as DataCurationRouteImport } from './routes/data-curation'
import { Route as DatasetsRouteImport } from './routes/datasets'
import { Route as EvaluationRouteImport } from './routes/evaluation'
import { Route as ExperimentsRouteImport } from './routes/experiments'
import { Route as ObservabilityRouteImport } from './routes/observability'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as AnnotationsIndexRouteImport } from './routes/annotations.index'
import { Route as AnnotationsExportsRouteImport } from './routes/annotations.exports'
import { Route as AnnotationsLabelRouteImport } from './routes/annotations.label'
import { Route as AnnotationsSourcesRouteImport } from './routes/annotations.sources'
import { Route as ObservabilityIndexRouteImport } from './routes/observability.index'
import { Route as ObservabilityExploreRouteImport } from './routes/observability.explore'
import { Route as ObservabilityMetricsRouteImport } from './routes/observability.metrics'
import { Route as ObservabilityQueryRouteImport } from './routes/observability.query'
import { Route as ObservabilityRunsRouteImport } from './routes/observability.runs'
import { Route as PromptsIndexRouteImport } from './routes/prompts.index'
import { Route as PromptsNameRouteImport } from './routes/prompts.$name'
import { Route as RunsRunIdRouteImport } from './routes/runs.$runId'
import { Route as TrainingIndexRouteImport } from './routes/training.index'
import { Route as TrainingModelsRouteImport } from './routes/training.models'
import { Route as TrainingRunsRouteImport } from './routes/training.runs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnotationsRoute = AnnotationsRouteImport.update({
  id: '/annotations',
  path: '/annotations',
  getParentRoute: () => rootRouteImport,
} as any)
const DataCurationRoute = DataCurationRouteImport.update({
  id: '/data-curation',
  path: '/data-curation',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsRoute = DatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationRoute = EvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentsRoute = ExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservabilityRoute = ObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnotationsIndexRoute = AnnotationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnnotationsRoute,
} as any)
const AnnotationsExportsRoute = AnnotationsExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => AnnotationsRoute,
} as any)
const AnnotationsLabelRoute = AnnotationsLabelRouteImport.update({
  id: '/label',
  path: '/label',
  getParentRoute: () => AnnotationsRoute,
} as any)
const AnnotationsSourcesRoute = AnnotationsSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AnnotationsRoute,
} as any)
const ObservabilityIndexRoute = ObservabilityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ObservabilityRoute,
} as any)
const ObservabilityExploreRoute = ObservabilityExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => ObservabilityRoute,
} as any)
const ObservabilityMetricsRoute = ObservabilityMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => ObservabilityRoute,
} as any)
const ObservabilityQueryRoute = ObservabilityQueryRouteImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => ObservabilityRoute,
} as any)
const ObservabilityRunsRoute = ObservabilityRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => ObservabilityRoute,
} as any)
const PromptsIndexRoute = PromptsIndexRouteImport.update({
  id: '/prompts/',
  path: '/prompts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsNameRoute = PromptsNameRouteImport.update({
  id: '/prompts/$name',
  path: '/prompts/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingIndexRoute = TrainingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrainingRoute,
} as any)
const TrainingModelsRoute = TrainingModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => TrainingRoute,
} as any)
const TrainingRunsRoute = TrainingRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => TrainingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/annotations': typeof AnnotationsRouteWithChildren
  '/data-curation': typeof DataCurationRoute
  '/datasets': typeof DatasetsRoute
  '/evaluation': typeof EvaluationRoute
  '/experiments': typeof ExperimentsRoute
  '/observability': typeof ObservabilityRouteWithChildren
  '/training': typeof TrainingRouteWithChildren
  '/workflows': typeof WorkflowsRoute
  '/annotations/exports': typeof AnnotationsExportsRoute
  '/annotations/label': typeof AnnotationsLabelRoute
  '/annotations/sources': typeof AnnotationsSourcesRoute
  '/observability/explore': typeof ObservabilityExploreRoute
  '/observability/metrics': typeof ObservabilityMetricsRoute
  '/observability/query': typeof ObservabilityQueryRoute
  '/observability/runs': typeof ObservabilityRunsRoute
  '/prompts/$name': typeof PromptsNameRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/training/models': typeof TrainingModelsRoute
  '/training/runs': typeof TrainingRunsRoute
  '/annotations/': typeof AnnotationsIndexRoute
  '/observability/': typeof ObservabilityIndexRoute
  '/prompts/': typeof PromptsIndexRoute
  '/training/': typeof TrainingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data-curation': typeof DataCurationRoute
  '/datasets': typeof DatasetsRoute
  '/evaluation': typeof EvaluationRoute
  '/experiments': typeof ExperimentsRoute
  '/workflows': typeof WorkflowsRoute
  '/annotations/exports': typeof AnnotationsExportsRoute
  '/annotations/label': typeof AnnotationsLabelRoute
  '/annotations/sources': typeof AnnotationsSourcesRoute
  '/observability/explore': typeof ObservabilityExploreRoute
  '/observability/metrics': typeof ObservabilityMetricsRoute
  '/observability/query': typeof ObservabilityQueryRoute
  '/observability/runs': typeof ObservabilityRunsRoute
  '/prompts/$name': typeof PromptsNameRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/training/models': typeof TrainingModelsRoute
  '/training/runs': typeof TrainingRunsRoute
  '/annotations': typeof AnnotationsIndexRoute
  '/observability': typeof ObservabilityIndexRoute
  '/prompts': typeof PromptsIndexRoute
  '/training': typeof TrainingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/annotations': typeof AnnotationsRouteWithChildren
  '/data-curation': typeof DataCurationRoute
  '/datasets': typeof DatasetsRoute
  '/evaluation': typeof EvaluationRoute
  '/experiments': typeof ExperimentsRoute
  '/observability': typeof ObservabilityRouteWithChildren
  '/training': typeof TrainingRouteWithChildren
  '/workflows': typeof WorkflowsRoute
  '/annotations/exports': typeof AnnotationsExportsRoute
  '/annotations/label': typeof AnnotationsLabelRoute
  '/annotations/sources': typeof AnnotationsSourcesRoute
  '/observability/explore': typeof ObservabilityExploreRoute
  '/observability/metrics': typeof ObservabilityMetricsRoute
  '/observability/query': typeof ObservabilityQueryRoute
  '/observability/runs': typeof ObservabilityRunsRoute
  '/prompts/$name': typeof PromptsNameRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/training/models': typeof TrainingModelsRoute
  '/training/runs': typeof TrainingRunsRoute
  '/annotations/': typeof AnnotationsIndexRoute
  '/observability/': typeof ObservabilityIndexRoute
  '/prompts/': typeof PromptsIndexRoute
  '/training/': typeof TrainingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/annotations'
    | '/data-curation'
    | '/datasets'
    | '/evaluation'
    | '/experiments'
    | '/observability'
    | '/training'
    | '/workflows'
    | '/annotations/exports'
    | '/annotations/label'
    | '/annotations/sources'
    | '/observability/explore'
    | '/observability/metrics'
    | '/observability/query'
    | '/observability/runs'
    | '/prompts/$name'
    | '/runs/$runId'
    | '/training/models'
    | '/training/runs'
    | '/annotations/'
    | '/observability/'
    | '/prompts/'
    | '/training/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data-curation'
    | '/datasets'
    | '/evaluation'
    | '/experiments'
    | '/workflows'
    | '/annotations/exports'
    | '/annotations/label'
    | '/annotations/sources'
    | '/observability/explore'
    | '/observability/metrics'
    | '/observability/query'
    | '/observability/runs'
    | '/prompts/$name'
    | '/runs/$runId'
    | '/training/models'
    | '/training/runs'
    | '/annotations'
    | '/observability'
    | '/prompts'
    | '/training'
  id:
    | '__root__'
    | '/'
    | '/annotations'
    | '/data-curation'
    | '/datasets'
    | '/evaluation'
    | '/experiments'
    | '/observability'
    | '/training'
    | '/workflows'
    | '/annotations/exports'
    | '/annotations/label'
    | '/annotations/sources'
    | '/observability/explore'
    | '/observability/metrics'
    | '/observability/query'
    | '/observability/runs'
    | '/prompts/$name'
    | '/runs/$runId'
    | '/training/models'
    | '/training/runs'
    | '/annotations/'
    | '/observability/'
    | '/prompts/'
    | '/training/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnotationsRoute: typeof AnnotationsRouteWithChildren
  DataCurationRoute: typeof DataCurationRoute
  DatasetsRoute: typeof DatasetsRoute
  EvaluationRoute: typeof EvaluationRoute
  ExperimentsRoute: typeof ExperimentsRoute
  ObservabilityRoute: typeof ObservabilityRouteWithChildren
  TrainingRoute: typeof TrainingRouteWithChildren
  WorkflowsRoute: typeof WorkflowsRoute
  PromptsNameRoute: typeof PromptsNameRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
  PromptsIndexRoute: typeof PromptsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annotations': {
      id: '/annotations'
      path: '/annotations'
      fullPath: '/annotations'
      preLoaderRoute: typeof AnnotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-curation': {
      id: '/data-curation'
      path: '/data-curation'
      fullPath: '/data-curation'
      preLoaderRoute: typeof DataCurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets': {
      id: '/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof DatasetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation': {
      id: '/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiments': {
      id: '/experiments'
      path: '/experiments'
      fullPath: '/experiments'
      preLoaderRoute: typeof ExperimentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observability': {
      id: '/observability'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof ObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annotations/': {
      id: '/annotations/'
      path: '/'
      fullPath: '/annotations/'
      preLoaderRoute: typeof AnnotationsIndexRouteImport
      parentRoute: typeof AnnotationsRoute
    }
    '/annotations/exports': {
      id: '/annotations/exports'
      path: '/exports'
      fullPath: '/annotations/exports'
      preLoaderRoute: typeof AnnotationsExportsRouteImport
      parentRoute: typeof AnnotationsRoute
    }
    '/annotations/label': {
      id: '/annotations/label'
      path: '/label'
      fullPath: '/annotations/label'
      preLoaderRoute: typeof AnnotationsLabelRouteImport
      parentRoute: typeof AnnotationsRoute
    }
    '/annotations/sources': {
      id: '/annotations/sources'
      path: '/sources'
      fullPath: '/annotations/sources'
      preLoaderRoute: typeof AnnotationsSourcesRouteImport
      parentRoute: typeof AnnotationsRoute
    }
    '/observability/': {
      id: '/observability/'
      path: '/'
      fullPath: '/observability/'
      preLoaderRoute: typeof ObservabilityIndexRouteImport
      parentRoute: typeof ObservabilityRoute
    }
    '/observability/explore': {
      id: '/observability/explore'
      path: '/explore'
      fullPath: '/observability/explore'
      preLoaderRoute: typeof ObservabilityExploreRouteImport
      parentRoute: typeof ObservabilityRoute
    }
    '/observability/metrics': {
      id: '/observability/metrics'
      path: '/metrics'
      fullPath: '/observability/metrics'
      preLoaderRoute: typeof ObservabilityMetricsRouteImport
      parentRoute: typeof ObservabilityRoute
    }
    '/observability/query': {
      id: '/observability/query'
      path: '/query'
      fullPath: '/observability/query'
      preLoaderRoute: typeof ObservabilityQueryRouteImport
      parentRoute: typeof ObservabilityRoute
    }
    '/observability/runs': {
      id: '/observability/runs'
      path: '/runs'
      fullPath: '/observability/runs'
      preLoaderRoute: typeof ObservabilityRunsRouteImport
      parentRoute: typeof ObservabilityRoute
    }
    '/prompts/': {
      id: '/prompts/'
      path: '/prompts'
      fullPath: '/prompts/'
      preLoaderRoute: typeof PromptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts/$name': {
      id: '/prompts/$name'
      path: '/prompts/$name'
      fullPath: '/prompts/$name'
      preLoaderRoute: typeof PromptsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/': {
      id: '/training/'
      path: '/'
      fullPath: '/training/'
      preLoaderRoute: typeof TrainingIndexRouteImport
      parentRoute: typeof TrainingRoute
    }
    '/training/models': {
      id: '/training/models'
      path: '/models'
      fullPath: '/training/models'
      preLoaderRoute: typeof TrainingModelsRouteImport
      parentRoute: typeof TrainingRoute
    }
    '/training/runs': {
      id: '/training/runs'
      path: '/runs'
      fullPath: '/training/runs'
      preLoaderRoute: typeof TrainingRunsRouteImport
      parentRoute: typeof TrainingRoute
    }
  }
}

interface AnnotationsRouteChildren {
  AnnotationsExportsRoute: typeof AnnotationsExportsRoute
  AnnotationsLabelRoute: typeof AnnotationsLabelRoute
  AnnotationsSourcesRoute: typeof AnnotationsSourcesRoute
  AnnotationsIndexRoute: typeof AnnotationsIndexRoute
}

const AnnotationsRouteChildren: AnnotationsRouteChildren = {
  AnnotationsExportsRoute: AnnotationsExportsRoute,
  AnnotationsLabelRoute: AnnotationsLabelRoute,
  AnnotationsSourcesRoute: AnnotationsSourcesRoute,
  AnnotationsIndexRoute: AnnotationsIndexRoute,
}

const AnnotationsRouteWithChildren = AnnotationsRoute._addFileChildren(
  AnnotationsRouteChildren,
)

interface ObservabilityRouteChildren {
  ObservabilityExploreRoute: typeof ObservabilityExploreRoute
  ObservabilityMetricsRoute: typeof ObservabilityMetricsRoute
  ObservabilityQueryRoute: typeof ObservabilityQueryRoute
  ObservabilityRunsRoute: typeof ObservabilityRunsRoute
  ObservabilityIndexRoute: typeof ObservabilityIndexRoute
}

const ObservabilityRouteChildren: ObservabilityRouteChildren = {
  ObservabilityExploreRoute: ObservabilityExploreRoute,
  ObservabilityMetricsRoute: ObservabilityMetricsRoute,
  ObservabilityQueryRoute: ObservabilityQueryRoute,
  ObservabilityRunsRoute: ObservabilityRunsRoute,
  ObservabilityIndexRoute: ObservabilityIndexRoute,
}

const ObservabilityRouteWithChildren = ObservabilityRoute._addFileChildren(
  ObservabilityRouteChildren,
)

interface TrainingRouteChildren {
  TrainingModelsRoute: typeof TrainingModelsRoute
  TrainingRunsRoute: typeof TrainingRunsRoute
  TrainingIndexRoute: typeof TrainingIndexRoute
}

const TrainingRouteChildren: TrainingRouteChildren = {
  TrainingModelsRoute: TrainingModelsRoute,
  TrainingRunsRoute: TrainingRunsRoute,
  TrainingIndexRoute: TrainingIndexRoute,
}

const TrainingRouteWithChildren = TrainingRoute._addFileChildren(
  TrainingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnotationsRoute: AnnotationsRouteWithChildren,
  DataCurationRoute: DataCurationRoute,
  DatasetsRoute: DatasetsRoute,
  EvaluationRoute: EvaluationRoute,
  ExperimentsRoute: ExperimentsRoute,
  ObservabilityRoute: ObservabilityRouteWithChildren,
  TrainingRoute: TrainingRouteWithChildren,
  WorkflowsRoute: WorkflowsRoute,
  PromptsNameRoute: PromptsNameRoute,
  RunsRunIdRoute: RunsRunIdRoute,
  PromptsIndexRoute: PromptsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
