//! The credential a single-user install authenticates with.
//!
//! A fourth mode rather than a widening of [`IngestToken`](crate::IngestToken),
//! and the reason is the guardrail that already stands: an ingest token is at
//! most an [`Role::Editor`], because it is a shared secret sitting in an
//! agent's environment and a leaked environment file must not be able to ask an
//! orchestrator to run something. That reasoning is about *where the secret
//! lives*, and it does not describe this one. A local token is generated by the
//! person at the keyboard, written to a file only they can read, and presented
//! by a process on the same machine to a server bound to the loopback
//! interface. Making it an editor would leave the owner of a laptop unable to
//! use their own installation — rerunning a workflow and reading a conversation
//! they recorded themselves both need `admin` — so it is an `admin`, and the
//! thing that makes that sound is stated as a start-up condition rather than
//! assumed: see [`LocalAuth::check_reachable`].
//!
//! There is no `local` mode without a token. A mode that authenticated nobody
//! would be [`AuthMode::None`](crate::AuthMode) under a name that reads like
//! protection, and this crate already has one of those with an honest name.

use crate::identity::{Credential, Identity, Role};
use crate::signing::{constant_time_eq, random_token};
use crate::{AuthError, AuthResult};

/// How the local token is presented, so a person reading a log or a curl line
/// can tell which of the two bearer shapes they are looking at.
pub const SUBJECT: &str = "local";

/// The local credential, and what it authenticates as.
#[derive(Clone)]
pub struct LocalAuth {
    secret: String,
    role: Role,
}

impl std::fmt::Debug for LocalAuth {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("LocalAuth")
            .field("role", &self.role)
            .finish_non_exhaustive()
    }
}

impl LocalAuth {
    /// A local credential over an existing secret.
    ///
    /// # Errors
    ///
    /// [`AuthError::Configuration`] when the secret is empty or too short to be
    /// worth checking — the same bar an ingest token is held to, and refused at
    /// start-up for the same reason: a guessable shared secret is worse than no
    /// authentication, because it looks like authentication.
    pub fn new(secret: impl Into<String>, role: Role) -> AuthResult<Self> {
        let secret = secret.into();
        let secret = secret.trim().to_owned();
        if secret.chars().count() < crate::MIN_TOKEN_LENGTH {
            return Err(AuthError::Configuration(format!(
                "the local token is shorter than {} characters; \
                 generate one with `aiwatcher token create`",
                crate::MIN_TOKEN_LENGTH
            )));
        }
        Ok(Self { secret, role })
    }

    /// A fresh secret, from the system random number generator.
    ///
    /// Here rather than in the CLI because this is the side that decides
    /// whether a secret is acceptable, and a generator that produced something
    /// [`Self::new`] would refuse is a bug nobody would find until the next
    /// start-up.
    ///
    /// # Errors
    ///
    /// [`AuthError::Configuration`] when the system random number generator
    /// fails, which is not a condition to paper over.
    pub fn generate() -> AuthResult<String> {
        random_token()
    }

    /// The caller a matching token authenticates as.
    #[must_use]
    pub fn identity(&self) -> Identity {
        Identity {
            subject: format!("token:{SUBJECT}"),
            username: Some(SUBJECT.to_owned()),
            name: None,
            email: None,
            groups: Vec::new(),
            roles: vec![self.role],
            expires_at: None,
            // Empty, and read as unrestricted because of the credential rather
            // than because of the list — see `Identity::may_claim`. A single
            // user install runs its own reactors and its own workers, and a
            // mode that added a token and took claiming away would mean
            // adopting the credential broke that machine.
            queues: Vec::new(),
            credential: Credential::Local,
        }
    }

    /// The identity, when what was presented is the secret.
    ///
    /// Constant-time, for the reason every other comparison in this crate is:
    /// the comparison *is* the check, and one that stops at the first differing
    /// byte reports the length of a correct prefix.
    #[must_use]
    pub fn authenticate(&self, presented: &str) -> Option<Identity> {
        constant_time_eq(self.secret.as_bytes(), presented.as_bytes()).then(|| self.identity())
    }

    /// What this credential grants.
    #[must_use]
    pub const fn role(&self) -> Role {
        self.role
    }

    /// Whether an address is one this credential was designed for.
    ///
    /// `local` grants `admin` on the strength of the machine boundary, so the
    /// machine boundary has to exist. A server bound to `0.0.0.0` with this
    /// mode on is handing an administrator's token check to anybody who can
    /// reach the port — which on a laptop on a café network is everybody.
    ///
    /// It is a *check* rather than a refusal because there is one legitimate
    /// case — a container, where binding the loopback interface would mean
    /// nothing could reach it at all — and the caller decides what to do with
    /// the answer. See the escape hatch in `aiwatcher-server`'s configuration.
    #[must_use]
    pub fn check_reachable(listen: std::net::IpAddr) -> bool {
        listen.is_loopback()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn auth() -> LocalAuth {
        LocalAuth::new(LocalAuth::generate().expect("generates"), Role::Admin).expect("accepts")
    }

    #[test]
    fn a_generated_token_is_one_this_module_would_accept() {
        // The generator and the bar it has to clear are on the same side, so
        // this cannot drift into a start-up failure nobody could explain.
        let secret = LocalAuth::generate().expect("generates");
        LocalAuth::new(secret, Role::Admin).expect("accepts its own output");
    }

    #[test]
    fn a_short_secret_is_refused_where_the_person_who_chose_it_is_watching() {
        let error = LocalAuth::new("hunter2", Role::Admin).expect_err("refuses");
        assert!(matches!(error, AuthError::Configuration(_)));
    }

    #[test]
    fn the_local_token_authenticates_as_an_admin() {
        let secret = LocalAuth::generate().expect("generates");
        let auth = LocalAuth::new(secret.clone(), Role::Admin).expect("accepts");
        let identity = auth.authenticate(&secret).expect("matches");
        assert!(identity.can(Role::Admin));
        assert_eq!(identity.username.as_deref(), Some(SUBJECT));
    }

    #[test]
    fn a_wrong_token_authenticates_as_nobody() {
        let auth = auth();
        assert!(auth.authenticate("not the secret").is_none());
    }

    #[test]
    fn a_prefix_of_the_token_is_not_the_token() {
        let secret = LocalAuth::generate().expect("generates");
        let auth = LocalAuth::new(secret.clone(), Role::Admin).expect("accepts");
        assert!(auth.authenticate(&secret[..secret.len() - 1]).is_none());
    }

    #[test]
    fn the_local_token_may_claim_any_queue_because_the_machine_dispatched_it() {
        let auth = auth();
        assert!(auth.identity().may_claim("anything"));
    }

    #[test]
    fn a_loopback_address_is_the_boundary_this_mode_rests_on() {
        assert!(LocalAuth::check_reachable(
            "127.0.0.1".parse().expect("parses")
        ));
        assert!(LocalAuth::check_reachable("::1".parse().expect("parses")));
        assert!(!LocalAuth::check_reachable(
            "0.0.0.0".parse().expect("parses")
        ));
    }
}
